name: Build and Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'  # Use a supported version

      # Step 3: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          pip install poetry==1.8.5
          poetry install

      # Step 4: Run tests
      - name: Run tests
        run: poetry run python -m pytest tests/test_api.py

      # Step 5: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Step 6: Authenticate Heroku CLI
      - name: Authenticate Heroku CLI
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Step 7: Set Heroku stack to container
      - name: Set Heroku stack to container
        run: heroku stack:set container -a $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      # Step 8: Log in to Heroku container registry
      - name: Log in to Heroku container registry
        run: |
          echo $HEROKU_API_KEY | docker login --username=$HEROKU_EMAIL --password-stdin registry.heroku.com
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Step 9: Build the Docker image
      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      # Step 10: Push the Docker image to Heroku
      - name: Push Docker image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Step 11: Release the newly pushed Docker image
      - name: Release app on Heroku
        run: |
          heroku container:release web -a $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
